// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAiBk5oSzBkTcAQ_r1ZEGRQzFc5LcNptFk',
    appId: '1:702930088228:web:7ae1d8bee421e5a9a243b1',
    messagingSenderId: '702930088228',
    projectId: 'student-ride-app',
    authDomain: 'student-ride-app.firebaseapp.com',
    storageBucket: 'student-ride-app.firebasestorage.app',
    measurementId: 'G-VBKZ7J3XED',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_7AF9IXM6Af5SGHFldtXxu-nYP7z2P4k',
    appId: '1:702930088228:android:9e0e429f75b7a4e8a243b1',
    messagingSenderId: '702930088228',
    projectId: 'student-ride-app',
    storageBucket: 'student-ride-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_dz0fPOOfxDD7MAtzd9QCX_lsT-D9Xz4',
    appId: '1:702930088228:ios:fcd6b5a8fdbf9c7fa243b1',
    messagingSenderId: '702930088228',
    projectId: 'student-ride-app',
    storageBucket: 'student-ride-app.firebasestorage.app',
    iosBundleId: 'com.example.studentRideApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_dz0fPOOfxDD7MAtzd9QCX_lsT-D9Xz4',
    appId: '1:702930088228:ios:fcd6b5a8fdbf9c7fa243b1',
    messagingSenderId: '702930088228',
    projectId: 'student-ride-app',
    storageBucket: 'student-ride-app.firebasestorage.app',
    iosBundleId: 'com.example.studentRideApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAiBk5oSzBkTcAQ_r1ZEGRQzFc5LcNptFk',
    appId: '1:702930088228:web:b8710c61c8e57a9ca243b1',
    messagingSenderId: '702930088228',
    projectId: 'student-ride-app',
    authDomain: 'student-ride-app.firebaseapp.com',
    storageBucket: 'student-ride-app.firebasestorage.app',
    measurementId: 'G-80GE4R1TFQ',
  );
}
